set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -ga terminal-overrides ",screen-256color*:Tc"
set -g default-terminal "screen-256color"
set -s escape-time 0

set -g mouse on

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.tmux.conf

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key -r i run-shell "tmux neww tmux-cht.sh"
bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/personal/todo.md"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set -g status-keys vi
setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

set -g status on
set -g status-interval 5
set -g status-justify left

set -g status-style fg=colour231,bg=colour233
set -g window-status-current-format ' #[fg=colour231,bg=colour104] #I │ #W #[bg=colour233,nobold]'
set -g window-status-format ' #[fg=colour181] #I │ #W '
set -g window-status-separator ''

set -g pane-border-style fg=colour233
set -g pane-active-border-style fg=colour104

set -g message-style fg=colour231,bg=colour239

set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#[fg=colour231,bg=colour104] #S #[bg=colour233,nobold]'
set -g status-right '#[fg=colour231,bg=colour104] #(git -C #{pane_current_path} branch 2>/dev/null | sed "s/* //") #[bg=colour233] #[fg=colour181]#{pane_current_path} '

setw -g automatic-rename on
set -g allow-rename on

set -g focus-events on

bind -n C-w run-shell "tmux neww -c '#{pane_current_path}'"
